name: Trigger dependent builds

on:
  push:
    branches: [main, master]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger auth build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Quintilis-Server/auth
          event-type: common-updated

      - name: Trigger forum build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Quintilis-Server/forum
          event-type: common-updated

      - name: Trigger gateway build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Quintilis-Server/gateway
          event-type: common-updated
